### ISSUE TITLE
compute_tag_cloud gives math domain error when using log10(0)

### ISSUE THREAD

**Issue by tuffnatty** [niconoe/django-nuages-tag#1]
I am not sure of the best way to fix it. I am just adding 0.1 to every value but this is not very nice.

**Comment by niconoe** [comment]
Thanks, this is indeed a bug that I'll fix very soon.

But we have two options here: if a tag is 0, should it appear at the minimum size, or simply not appear at all ? Do you have any opinion on this ?

**Comment by tuffnatty** [comment]
I'd say, an unused tag should not appear in the cloud. But it might be an option for other people.

**Comment by niconoe** [comment]
I agree. I'll release 0.1.2 soon to fix this issue !

**Comment by niconoe** [comment]
0.1.2 has just been released to fix this issue. Can you have a look ? Thanks.

**Comment by tuffnatty** [comment]
works fine for me! Thanks a lot!
