### ISSUE TITLE
Add COPYRIGHT and LICENSE file

### ISSUE THREAD

**Issue by rodo** [niconoe/django-nuages-tag#3]
Could you add a COPYRIGHT file and use a LICENSE file not modified, this will facilitate the packaging of your app.

Thanks a lot for It

**Comment by niconoe** [comment]
These files should follow Debian recommendations ?

I just added COPYRIGHT, taking example on the COPYRIGHT file in python-django-registration (0.8-2). I also added a small copyright line at the top of LICENSE.txt so it looks identical to the example on Wikipedia (this is a standard 3-clause BSD license).

I'm not familiar with these requirements, so feel free to report any other issue with this !

Thx !

**Comment by rodo** [comment]
Thanks a lot. Last advice to be perfect could you fill your paragraph at 79 columns ?

**Comment by rodo** [comment]
I made a package for Debian/Wheezy http://www.pydeb.eu/blog/django-nuages-tag-013/

**Comment by niconoe** [comment]
Thanks that's great ! I truncated the lines at 79 chars as asked.
